ci(workflow): log line 35 to 10

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -37,5 +37,5 @@ jobs:
           
           
           echo "Pushing changes to production..."
-          git push --force production main || { echo "Push failed"; exit 35; }
+          git push --force production main || { echo "Push failed"; exit 10; }
           echo "Push completed successfully."
